services:
  influxdb: 
    image: influxdb:latest
    container_name: influxdb-home-iot
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    env_file:
     - .env
    restart: always


  telegraf:
    image: telegraf:latest
    container_name: telegraf-home-iot
    depends_on:
      - influxdb
    env_file:
     - .env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana-home-iot
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
    restart: always

volumes:
  influxdb_data:
  grafana-storage: